# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  # Local only podspec will download source zip
#  pod 'AMapFoundation-NO-IDFA-XC', :path => '../'
  pod 'AMapFoundation-NO-IDFA-XC', :podspec => '../'

end
