# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'AMapFoundation-NO-IDFA-XC', :git => "https://github.com/SouHanaQiao/AMapFoundation-NO-IDFA-XC.git", :tag => '1.0.7'
end
